### ISSUE TITLE
Navigating away from page with jodit-angular give TypeError

### ISSUE THREAD

**Issue by itsmoirob** [jodit/jodit-angular#1]
When using jodit-angular I can get my page loading correctly, but when I navigate away from the page I get a `"TypeError: o.jodit.events is undefined"`

When I navigate routes between pages without jodit everything loads fine. When I navigate to a route with jodit everything loads fine. When I navigate **away** from jodit to **another** page that is when I get the error.

While looking in to stackoverflow answers I come across this https://github.com/xdan/jodit/issues/9#issuecomment-351070288 answer explaining how to use "vanilla" jodit with angular. It gives an action in ngOnDestroy to call this.editor.destruct(); Am I supposed to be taking actions similarly?

in my module.ts all the code I use relating to jodit

```
import { JoditAngularModule } from 'jodit-angular';
...
@NgModule({
imports: [
JoditAngularModule
]
})
``` 
In my html template I use 

```
<jodit-editor [config]="{}"> </jodit-editor>
```
Using 
jodit 3.1.5
jodit-angular 1.0.17
@angular/... 5.2.5
typescript 2.5.3
node 8.9.4

Full error
```
TypeError
    columnNumber: 34948
    fileName: "http://localhost:3001/mailandsms/vendor.bundle.js"
    lineNumber: 86746
    message: "o.jodit.events is undefined"
    stack: "t/o.immedateCheckActiveButtons@http://localhost:3001/mailandsms/vendor.bundle.js:86746:34948\n./node_modules/jodit/build/jodit.min.js/</</</t.debounce/</i<@http://localhost:3001/mailandsms/vendor.bundle.js:86746:8140\n./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:3001/mailandsms/polyfills.bundle.js:2435:17\nonInvokeTask@http://localhost:3001/mailandsms/vendor.bundle.js:47116:24\n./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:3001/mailandsms/polyfills.bundle.js:2434:17\n./node_modules/zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:3001/mailandsms/polyfills.bundle.js:2202:28\n./node_modules/zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:3001/mailandsms/polyfills.bundle.js:2510:24\nZoneTask/this.invoke@http://localhost:3001/mailandsms/polyfills.bundle.js:2499:28\ntimer@http://localhost:3001/mailandsms/polyfills.bundle.js:4039:17\n
    "__proto__: {…}
    constructor: function TypeError()message: ""name: "TypeError"stack: ""__proto__: {…}constructor: function Error()
    message: ""
    name: "Error"
    stack: Getter & Setter
    toSource: function toSource()
    toString: function toString()
    __proto__: Object { … } app-error-handler.ts:5:4

```

If you need any other details please let me know

EDIT: Additional info

If I go to line 86746 col 34948 where the error points to this is the block of code;

`o.jodit.events.fire("updateToolbar"))}`

**Comment by itsmoirob** [comment]
So while trying to figure out how to use setEditorValue and going through the source code, I see that you are using the code from https://github.com/xdan/jodit/issues/9#issuecomment-351070288 I removed this wrapper, used the code mentioned directly, and noticed that this error is also in that code.

After doing a quick investigation it appears the the ngOnDestroy isnt working correctly as the component is already destroyed before the call to jodit.destruct() can be fired. This can be linked to the feature request ngBeforeDestroy here https://github.com/angular/angular/issues/17404

Removing the ngOnDestroy will prevent the o.jodit.events undefined error from appearing, although a new method to run jodit.destruct() may be required.

**Comment by antony-booth** [comment]
I don't know whether this is related, but the behavior is the same: -


    core.js:1440 ERROR TypeError: Cannot read property 'fire' of undefined
    at e.o.immedateCheckActiveButtons (jodit.min.js:10) 
    at eval (jodit.min.js:10) 
    at ZoneDelegate.invokeTask (zone.js:421) 
    at Object.onInvokeTask (core.js:4724) 
    at ZoneDelegate.invokeTask (zone.js:420) 
    at Zone.runTask (zone.js:188) 
    at ZoneTask.invokeTask (zone.js:495) 
    at ZoneTask.invoke (zone.js:484) 
    at timer (zone.js:2065)

Navigating away from the editor with a routerLink.

It seems to be at this line (sorry it's the minified version of jodit.min): -
1451: `o.jodit.events.fire("updateToolbar"))`

I don't know if this resolves it, but I read that setting an element id for the editor with an alpha prefix, may resolve it. I.E: `<editor  id="a123"/>`, but as jodit-angular wraps it, I can't set it directly.

**Comment by xdan** [comment]
Hi, fixed. Thank you!

**Comment by GovindaRajbhar** [comment]
I am also facing the same issue 

ExecutiveSummaryComponent.html:13 ERROR TypeError: Cannot read property 'fire' of undefined
    at t.setEditorValue (jodit.min.js:10)
    at JoditAngularComponent.set [as value] (jodit-angular.js:92)
    at JoditAngularComponent.webpackJsonp.82e334896ad5897e90c8.JoditAngularComponent.writeValue (jodit-angular.js:142)
    at forms.js:2392
    at forms.js:3973
    at Array.forEach (<anonymous>)
    at FormControl.webpackJsonp.93200bbb0ebc67b1d3cd.FormControl.setValue (forms.js:3973)
    at ExecutiveSummaryComponent.webpackJsonp.82e334896ad5897e90c8.ExecutiveSummaryComponent.resetForm (executive-summary.component.ts:171)
    at ExecutiveSummaryComponent.webpackJsonp.82e334896ad5897e90c8.ExecutiveSummaryComponent.toggleIsCollapsed (executive-summary.component.ts:177)
    at Object.eval [as handleEvent] (ExecutiveSummaryComponent.html:13)
