### ISSUE TITLE
package is not working with typescripts noImplicitAny set to true

### ISSUE THREAD

**Issue by atakchidi** [jodit/jodit-angular#10]
When typescripts option noImplicitAny is set to true, building the app result in the following error: 

ERROR in node_modules/jodit-angular/Events.d.ts(2,19): error TS7016: Could not find a declaration file for module 'jodit'. '/home/alex/projects/rwl/front/ngx-client/src/node_modules/jodit/build/jodit.min.js' implicitly has an 'any' type.

This happens because module should have proper declaration to be compatible with typescripts noImplicitAny.
https://github.com/Microsoft/TypeScript/issues/15031 

Please make it possible to compile with noImplicitAny options set to true, cause this feature may preserve a lot of errors, but your package is forcing people to turn this of for now.

P.S another way to avoid this is to set  skipLibCheck: true introduced in ts 2.0 but it still seems not the right way to do things

**Comment by ghost** [comment]
+1

**Comment by bergmito** [comment]
+1

**Comment by RenanLopes77** [comment]
+1

**Comment by brunochikuji** [comment]
+1

**Comment by edureis** [comment]
+1
