### ISSUE TITLE
Angular 13 support

### ISSUE THREAD

**Issue by crlsmsq** [jodit/jodit-angular#101]
Hi. Would it be possible to support Angular 13?
![image](https://user-images.githubusercontent.com/80941041/163100001-af9bf361-36a2-4fa0-ad27-d9e846a24fba.png)getting this error

**Comment by MrElectroNick** [comment]
Hi @crlsmsq definitely yes! During this week new version with Angular 13 support will be available. Stay tuned!

**Comment by sskasim** [comment]
Hi @MrElectroNick, Any chance that you may have Angular 13 support soon?
Thanks

**Comment by melvinotieno** [comment]
Hi @MrElectroNick , any progress on this?

**Comment by MrElectroNick** [comment]
@sskasim @melvinotieno Hi, I'll try to catch up with this upcoming weekend! Thanks for pinging me on this thing!

**Comment by SHELA** [comment]
Hello @[MrElectroNick](https://github.com/MrElectroNick),
Have any news on updates?

**Comment by MrElectroNick** [comment]
Hi @SHELA Not yet. Project where I use jodit as angular component has not yet been migrated to v13 so I can't make an upgrade yet. But soon it should move on in this direction. Sorry for a delay - crazy things happening in the world

**Comment by SHELA** [comment]
@[MrElectroNick](https://github.com/MrElectroNick) Харькову держаться

**Comment by IngalePushkar** [comment]
@MrElectroNick  Any progress on this ?

**Comment by Shoti2313** [comment]
I think its nice to support Angular 14 too

**Comment by Omzig** [comment]
@MrElectroNick Can you create a blank project or an angular Tour of Heroes app for each version and then produce updates to the repo for this package?

I am in need of v13, soon i will move to 14, i am about 6 months behind on each because of lagging packages.

Please and thank you.

@xdan Can you help?


I had to run --force on the package...

> c:\\> npm start
> Warning: C:\Users\.......\src\app\app.module.ts depends on 'jodit-angular'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by julianpoemp** [comment]
Dear @MrElectroNick and other developers,

can you please upgrade this package to later Angular versions? For compatibility you could create a branch for each version of Angular and a new naming convention:

v4.x branch => Angular 12
v5.x branch => Angular 13
v6.x branch => Angular 14

New features could be implemented on a separate branch that can be merged into the other version branches.

That is what other big projects do. If this is too much overhead we all would appreciate if you at least upgrade to Angular 12.

**Comment by Omzig** [comment]
> Dear @MrElectroNick and other developers,
> 
> can you please upgrade this package to later Angular versions? For compatibility you could create a branch for each version of Angular and a new naming convention:
> 
> v4.x branch => Angular 12 v5.x branch => Angular 13 v6.x branch => Angular 14
> 
> New features could be implemented on a separate branch that can be merged into the other version branches.
> 
> That is what other big projects do. If this is too much overhead we all would appreciate if you at least upgrade to Angular 12.

@julianpoemp  Umm.... he lives in the Ukraine..... this might be a problem for the repo.

**Comment by xdan** [comment]
@julianpoemp @Omzig Maybe you can do it yourself and submit a PR? I don't use Angular at all in my projects and I don't understand it. And @MrElectroNick I think now there are other problems(

**Comment by julianpoemp** [comment]
@Omzig I'm sorry, I didn't know he lives in Ukraine...

@xdan I'm thinking about creating a new repository because I'd like to use [Nx](https://nx.dev/) because it offers a lot of features to make development easier and I would have full access to create new updates and releases to npm.

**EDIT:** I created an Angular wrapper for Jodit that is compatible to Angular >= 12 and supports the latest version of Jodit: [ngx-jodit](https://github.com/julianpoemp/ngx-jodit)

**Comment by MrElectroNick** [comment]
@julianpoemp @Omzig @IngalePushkar @SHELA @melvinotieno @sskasim Libraries for angular v13 and v14 has been released. But during integration into my project I see some issues related to dynamic loading of jodit itself. So now I'm working on resolving this. You can try v1.13.* and v.14.* but if you get issues with it - know I'm on this right now.
Also - I'm not in Ukraine but in Podgorica (Montenegro) right now - it was just a harsh summer and I honestly wasn't around and work related to Jodit

**Comment by MrElectroNick** [comment]
I've released new version for Angular 13 - please use 1.13.6 if you experienced "reqire" exception in v1.13.5
Work on v14 wrapper is on the way

**Comment by Omzig** [comment]
> I've released new version for Angular 13 - please use 1.13.6 if you experienced "reqire" exception in v1.13.5 Work on v14 wrapper is on the way

TY, hope you are safe, we really enjoy your work.

**Comment by MrElectroNick** [comment]
> > I've released new version for Angular 13 - please use 1.13.6 if you experienced "reqire" exception in v1.13.5 Work on v14 wrapper is on the way
> 
> TY, hope you are safe, we really enjoy your work.

@Omzig I'm fine. Not in Ukraine. But I'm 24/7 mentally there :-(

**Comment by MrElectroNick** [comment]
Versions for Angular 13 and Angular 14 has been released
