### ISSUE TITLE
Buttons with downlist icons inside 'dots' is not working in Ionic Project-Mobile

### ISSUE THREAD

**Issue by ghost** [jodit/jodit-angular#11]
Buttons with downlist icons like 'fontsize', 'image', or even 'link' button which opens a new 'box' is not working if they are inside 'dots' using Mobile | Chrome (Android) | Chrome (IOS) in an Ionic Project.

I did some tests with Angular blank project (without Ionic).. everything triggers fine (desktop/mobile).
But with an Angular-Ionic project, anything happens when I touch that buttons.. (only in mobile.. desktop is fine)

https://github.com/stt065907/jodit-angular-ionic

![screenshot from 2018-05-28 18-00-51](https://user-images.githubusercontent.com/27783572/40629479-c5b1f2b6-62a1-11e8-93a2-9d492cf391b2.png)

**Comment by bergmito** [comment]
I have the same problem. =(

**Comment by xdan** [comment]
Try in 3.2.7 please
