### ISSUE TITLE
Current Install Steps For Angular Project

### ISSUE THREAD

**Issue by szarkowicz** [jodit/jodit-angular#12]
Hi,

I am following the current install steps found at this link - [Angular jodit Install](https://xdsoft.net/jodit/examples/intergration/angular-jodit.html) for installing into an Angular 5 CLI and also tried in an Angular 6 CLI project. 

After following the install steps - I am receiving the following error

`
ERROR Error: StaticInjectorError(AppModule)[JoditAngularComponent -> ElementRef]: 
  StaticInjectorError(Platform: core)[JoditAngularComponent -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
`

![screen shot 2018-06-18 at 3 03 35 pm](https://user-images.githubusercontent.com/9085693/41559168-df8c7ffe-7308-11e8-8750-3d544947841d.png)

Current Setup

**App.module.ts**
`
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';

import { AppComponent } from './app.component';

import { JoditAngularModule } from 'jodit-angular';

@NgModule({
  imports:      [ BrowserModule, FormsModule, JoditAngularModule ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
`

**app.component.ts**
`
<p>
  Start editing to see some magic happen :)
</p>

<jodit-editor [config]="{buttons: 'bold'}"></jodit-editor>
`

**Package.json**
"jodit-angular": "^1.0.56",

Here is the link to the [stackblitz](https://stackblitz.com/edit/angular6-jodit-example) example code:
https://stackblitz.com/edit/angular6-jodit-example

Please let me know if the current directions are missing a step or need to be updated.

Thanks in advanced

**Comment by alekpentchev** [comment]
I have the same issue, any ideas how to fix it?

EDIT: And the syntax highlight underlines the jodit html tag telling it's not a known element.

**Comment by alekpentchev** [comment]
@szarkowicz I've found a solution for this issue which works for me.

The things I did:
1. Uninstall jodit-angular
2. Copy 'jodit-angular' folder from the example in this repo and paste it somewhere appropriate in your project
3. In the module where you declare the component which'll use jodit import JoditAngularModue, add it to imports or to exports eventually, too (if it's needed).

Now it should be fine. Let me know if this worked for you. And yes, I know it's not the best solution, I'll try to solve it with proper npm package installation.

EDIT: Funny thing. After completing above mentioned steps which worked I tried to do it once more as it is in the instruction. The only two things I did were installing jodit-angular again (I have jodit installed, too) and adding importing JoditAngularModule in the module.

**Comment by Shrewd** [comment]
I'm having this issue too in angular 5

Angular CLI: 1.7.4
Node: 8.11.2
OS: win32 x64
Angular: 5.2.11

**Comment by alekpentchev** [comment]
@Shrewd Did you try my "solution" - the steps and then from the 'EDIT' section?
I can't explain why it worked but now it works.

**Comment by Shrewd** [comment]
@alekpentchev I wasn't sure about where to put the folder, but now I'm guessing you're using it as a made component inside your app folder, right?
I'll give it a try later, but for now I just wanted to confirm the issue.

**Comment by alekpentchev** [comment]
@Shrewd I put it in the root directory and then imported the JoditAngularModule (or how is it called) in the module I needed it in. Then it worked.

But still, when I deleted the folder and installed the package via npm and then imported the module, it worked fine. I don't know why, but Angular stopped whining.

**Comment by Shrewd** [comment]
Hi @alekpentchev  I managed it to work. I unziped the folder in project/src/app.
So it creates the folder and component files are in src\app\jodit-angular

Using `import { JoditAngularModule} from './jodit-angular/jodit-angular.module';` seems to work.

But **npm package is still necesary**, jodit-angular.component points to `../node_modules/jodit/build/jodit.min.css`

You may have removed it from the angular.cli, but the package is still in node_modules.

Since I used a folder in my app, I needed to change jodit-angular.component to 
`styleUrls: ['../../../node_modules/jodit/build/jodit.min.css'],`

Then I got the editor showing.

**Comment by alekpentchev** [comment]
@Shrewd Ok, I see. I think this npm package is necessary since it's the regular Jodit editor which is a dependency of jodit-angular wrapper.

**Comment by alekpentchev** [comment]
Ok guys, the issue occured again, after trying to install other, completely unrelated npm package...This time my pseudo-solutions did not help.
So, it'd really great if the creator / contributors could take a look and help us.

**Comment by Romain-P** [comment]
still have the error on angular 8+

**Comment by ahsan-alii** [comment]
Thank you so much @shrewd, your solution worked perfectly  for me

**Comment by ErnestoSilvaAcevedo** [comment]
I tested it in Angular 8,
 
but the installations steps didn't work when I follow them.
Then I just added

  **npm install jodit**

After the first intruction:

  **npm install jodit-angular**

and everything worked!

This are my resulting entries in package.json:
    "jodit": "^3.3.24",
    "jodit-angular": "^1.0.99",
