### ISSUE TITLE
npm install creates an additional node_modules folder

### ISSUE THREAD

**Issue by FlorianMathis** [jodit/jodit-angular#13]
Hi,

**problem:**
by installing jodit-angular there will be generated an additional node_modules folder which ends in following error:  "Cannot redeclare block-schoped variable 'ngDevMode'.

**solution**
delete the generated node_modules folder (everything works fine then)

@xdan: Can you tell me why you locate another additional node_modules folder in your package?

**Comment by helix46** [comment]
Build gives error:
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**Comment by Shrewd** [comment]
In my case, using wrong angular versions made the error occur. 
Angular versions must match this library version, currently 5.2.11
I used `npm update` to do so, and then ng-bootstrap caused errors since it now requires angular 6.
Using `npm install --save @ng-bootstrap/ng-bootstrap@2.0.0` did the trick

**Comment by Iskuzer** [comment]
> Build gives error:
> ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
--
Same problem with angular 6

**Comment by helix46** [comment]
Work around...
I've had to delete the node_modules folder so often that I've made a script to go in package.json scripts:

"fix-jodit-node-modules": "fix-jodit-node-modules.bat",

Contents of fix-jodit-node-modules.bat (for windows of course):
 IF EXIST .\node_modules\jodit-angular\node_modules (
   rd .\node_modules\jodit-angular\node_modules /S /q
 )

**Comment by Raiper34** [comment]
Same problem Angular 6...

**Comment by garluk** [comment]
> Work around...
> I've had to delete the node_modules folder so often that I've made a script to go in package.json scripts:
> 
> "fix-jodit-node-modules": "fix-jodit-node-modules.bat",
> 
> Contents of fix-jodit-node-modules.bat (for windows of course):
> IF EXIST .\node_modules\jodit-angular\node_modules (
> rd .\node_modules\jodit-angular\node_modules /S /q
> )

This worked to me with Node.js 12.10: https://stackoverflow.com/a/57866165

In your package.json, add:

```
"scripts": {
    "postinstall": "path_to_your_script"
  }
```

Then, create a script in your project with the following:

```
const fs = require('fs');

fs.rmdirSync('node_modules/jodit-angular/node_modules', {recursive: true});
```

This will run when you npm install, so you don't have to manually delete the folder.
