### ISSUE TITLE
Databinding the editor's value

### ISSUE THREAD

**Issue by ddhille** [jodit/jodit-angular#14]
I'm wondering how the proper way to access the editor's value would look like. It's somehow missing in the readme. I'm currently using Jodit in my Ionic 3 app.

**.html**
```html
<jodit-editor #editor
    (onChange)="editorValueChanged(editor)"
    [config]="{
        uploader: { insertImageAsBase64URI: 'true' },
        buttons: 'bold,strikethrough,underline,italic,|,superscript,subscript,|,ul,ol,hr,paragraph,|,image,video,table,link,|,undo,redo,|,print',
        language: 'de'}">
</jodit-editor>
```

**.ts**
```typescript
editorValueChanged(editor) {
  editor.value = "somefunnytext"
}
```
This code is working. As soon as I type in some text in the editor, it gets replaced by "somefunnytet"...
BUT I naturally want my editor to let me set its value as soon as the page is loading. And not after I typed in some text (onChange).

_I'm pretty new to Angular and Ionic, so I might just lack some basic knowledge of how this is done properly._

**Comment by helix46** [comment]
I'm not using Ionic, but this works for me:

<form [formGroup]="myForm">
    <jodit-editor formControlName="myJodit">
    </jodit-editor>
</form>


  myForm: FormGroup;
  constructor(@Inject(FormBuilder) private builder: FormBuilder) {
    this.myForm = this.builder.group({
      myJodit: new FormControl('')
    });
  }


this.myForm.controls.myJodit.setValue(value);


let value: string = this.myForm.controls.myJodit.value;

More info here:
https://angular.io/guide/reactive-forms
