### ISSUE TITLE
Buttons for image, link, brush aren't working on mobile (buttons that generate a popup)

### ISSUE THREAD

**Issue by AAniculaesei-modus** [jodit/jodit-angular#21]
Hello,

I am using jodit-angular v1.0.69
The buttons for imag, link and brush aren't working on mobile (don't display the popup like they do on web)
This is a video of the issue:

https://screencast.com/t/0xiVQIU6RpN

**Comment by Scobee** [comment]
@xdan - Do you have any updates on this ? Also there is an issue with the package, it adds `node_modules` in the `jodit_angular` folder .. and I have to remove this every single time I do `npm install`
