### ISSUE TITLE
Backward compatibility break down

### ISSUE THREAD

**Issue by ddydeveloper** [jodit/jodit-angular#24]
Good morning! 

As I understand the app version 1.0.69 includes @angular dependencies updates to 7.x.x version. I use jodit-angular: ^1.0.59 @angular: 5.x.x in my application, so after 1.0.69 was published I got the following error:

> ERROR in ../jodit-angular/jodit-angular.ts(6,2): Error during template compile of 'JoditAngularModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

Suppose that it is because of the jodit-angular and my app @angular versions conflict. Looks like breaking changes 

Do you consider a way to publish the 2.x.x jodit-angular version? It can help to avoid confusing situations and allow not to use the particular version. like that:

    "dependencies": {
        "@angular/animations": "^5.2.0",
        "@angular/compiler": "^5.2.0",
        "@angular/core": "^5.2.0"
        .......
        "jodit-angular": "1.0.59",
        .......
     }

**Comment by AAniculaesei-modus** [comment]
Hey @ddydeveloper  - I have     "jodit": "^3.2.27", and "jodit-angular": "^1.0.81" on my app .. and I use it with Angular 5
The only issue I am facing is that I have to delete node_modules every single time :(

**Comment by MrElectroNick** [comment]
At this moment only Angular version 8 and higher are supported
