### ISSUE TITLE
Is there a way to customize the image downloading request to add token into the header

### ISSUE THREAD

**Issue by hoop22** [jodit/jodit-angular#36]
**Jodit-Angular Version:**  1.0.81

**Browser:**  Chrome
**OS:**  Windows

**Expected behavior:**
Image downloading request's hender can be sent with token as the following,
```
Accept: application/json
Authorization: Bearer 'token string here'
Referer: http://localhost:4200/sh/721408ea-2812-4c78-a737-611cab1f3102/account/tk
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
```

**Actual behavior:**
Havn't got a way to achieve this.

I've tried interceptor catching the request, and then add token to the request's header, but it looks like the interceptor cannot catch the image downloading request, still not sure why not.. Probably because jodit's using another http clients?

Is there a way to customize the image downloading request to add token into the header?

**Comment by MrElectroNick** [comment]
Hi @hoop22 please report this issue to [Jodit main repository](https://github.com/xdan/jodit/issues)
