### ISSUE TITLE
Upgrading from 1.0.17 to 1.0.18 or above causes Typescript / angular-cli error for Angular 5

### ISSUE THREAD

**Issue by antony-booth** [jodit/jodit-angular#4]
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): 
    error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

    node_modules/jodit-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11):
    error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

The issue seems to be the inclusion into the package of a specific version of `@angular/core`, so the variable ngDevMode is being declared twice in: -

    jodit-angular/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts

and 

    node_modules/@angular/core/src/render3/ng_dev_mode.d.ts

Here is the sample package.json.  Change `"jodit-angular": "1.0.17",` to `"jodit-angular": "1.0.18",` and `ng build` fails with the error above. This is true for all subsequent versions up to and including 1.0.27

	  "dependencies": {
		"@angular/animations": "^5.2.8",
		"@angular/cdk": "^5.2.4",
		"@angular/common": "^5.2.8",
		"@angular/compiler": "^5.2.8",
		"@angular/core": "^5.2.8",
		"@angular/flex-layout": "2.0.0-beta.10-4905443",
		"@angular/forms": "^5.2.8",
		"@angular/http": "^5.2.8",
		"@angular/material": "^5.2.4",
		"@angular/platform-browser": "^5.2.8",
		"@angular/platform-browser-dynamic": "^5.2.8",
		"@angular/router": "^5.2.8",
		"@aspnet/signalr-client": "^1.0.0-alpha2-final",
		"core-js": "^2.4.1",
		"font-awesome": "^4.7.0",
		"hammerjs": "^2.0.8",
		"honorific": "^1.0.2",
		"http-status-codes": "^1.3.0",
		"jodit-angular": "1.0.17",
		"jwt-decode": "^2.2.0",
		"rxjs": "^5.5.7",
		"zone.js": "^0.8.20"
	  },
	  "devDependencies": {
		"@angular/cli": "^1.7.3",
		"@angular/compiler-cli": "^5.2.8",
		"@angular/language-service": "^5.2.8",
		"@types/jasmine": "~2.5.53",
		"@types/jasminewd2": "~2.0.2",
		"@types/node": "^6.0.102",
		"angular-file": "^0.5.1",
		"codelyzer": "^4.2.1",
		"jasmine-core": "~2.6.2",
		"jasmine-spec-reporter": "~4.1.0",
		"json-stringify-safe": "^5.0.1",
		"karma": "~1.7.0",
		"karma-chrome-launcher": "~2.1.1",
		"karma-cli": "~1.0.1",
		"karma-coverage-istanbul-reporter": "^1.4.2",
		"karma-html-reporter": "^0.2.7",
		"karma-jasmine": "~1.1.0",
		"karma-jasmine-html-reporter": "^0.2.2",
		"karma-junit-reporter": "^1.2.0",
		"protractor": "~5.1.2",
		"ts-node": "~3.2.0",
		"tslint": "~5.7.0",
		"typescript": "2.6.2",
		"typescript-char": "0.0.0"
	  }

**Comment by antony-booth** [comment]
It's intermittent, so it must be a caching issue

**Comment by isherwood** [comment]
I'm seeing the same error with Angular 5.2.5 and Jodit-Angular 1.0.47. Did you learn anything more that might help? How does one clear the cache you mentioned? Thanks.

**Comment by antony-booth** [comment]
I can't remember, but I think I just purged the node_modules folder and ran npm install again.
