### ISSUE TITLE
Some issues found in the text editor are given 

### ISSUE THREAD

**Issue by nkjithin** [jodit/jodit-angular#43]
1.Bold or italic options are not working sometimes. Please refer the video attached TK270_5.
2.Select all option is not working properly. Please refer the video TK270_18.
[Issues.tar.gz](https://github.com/jodit/jodit-angular/files/4116263/Issues.tar.gz)

**Comment by MrElectroNick** [comment]
Hi @nkjithin please report this issue to [Jodit main repository](https://github.com/xdan/jodit/issues)
