### ISSUE TITLE
Typing content not visible in editor (in mobile devices)

### ISSUE THREAD

**Issue by onilleksh** [jodit/jodit-angular#47]
In mobile applications, If we type something in the editor and click device back button to navigate back while editing (focused state). Jodit is not responding afterwards where no content is visible in the editor even if you type.

More details: 

- Data is getting prefilled into editor on component init, but no new content is visible when typed

- onChange emits nothing

**Comment by MrElectroNick** [comment]
Hi @onilleksh please report this issue to [Jodit main repository](https://github.com/xdan/jodit/issues)
