### ISSUE TITLE
Angular directives used as a HTML element attributes are transformed to lower case

### ISSUE THREAD

**Issue by aniketrk** [jodit/jodit-angular#50]
Guys I have one issue I am using this editor in Angular 8 version. I am trying to pass html snippet through editor. But some how editor converts the element attributes to lower case for Example
`<div [ngSwitch]="x"></div>` is transformed to `<div [ngswitch]="x"></div>`
`<p [routerLink]="['/error']"></p>` is transformed to `<p [routerlink]="['/error']"></p>`

I even tried with **cleanhtml** but even that didn't help.

Have anyone faced this issue? 
Do we have any config option to avoid this?

Thanks In Advance.

**Comment by MrElectroNick** [comment]
Hi @aniketrk please report this issue to [Jodit main repository](https://github.com/xdan/jodit/issues)
