### ISSUE TITLE
Jodit 1.0.99 does not fully work with jodit 3.3.23+

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#51]
From what I'm testing and using `jodit-angular` for, I am not able to use the "resizer" plugin for image from `v3.3.23` of `jodit `and above. I'm using the latest jodit-angular package (just did `npm i angular-jodit`. Just for future releases, maybe that's something to look at.

At the moment, I got it working with `1.0.99` of `jodit-angular `combined with `3.3.22` `jodit`. I'm using `Angular 9.1.1`

Thanks for the great work!

**Comment by MrElectroNick** [comment]
Hi @CarlosTorrecillas please update to latest version according to ReadMe
