### ISSUE TITLE
Loading screen on project

### ISSUE THREAD

**Issue by SNaaz7** [jodit/jodit-angular#52]
Hello team, 
I am encountering an issue while using this library,
While using latest version (1.0.99), I'm getting an error as:-

ERROR in ./~/jodit-angular/fesm5/jodit-angular.js
Module not found: Error: Can't resolve 'jodit' in '/var/www/html/git/inteleagent/node_modules/jodit-angular/fesm5'
 @ ./~/jodit-angular/fesm5/jodit-angular.js 118:19-35
 @ ./src/app/shared/shared.module.ts
 @ ./src/app/frontend/frontend.module.ts
 @ ./src/app/app.module.ts
 @ ./src/app/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/app/main.ts

In version 1.0.85
My screen loader comes & it's never ending

While in version 1.0.22, my errror is
/var/www/html/git/inteleagent/node_modules/jodit/src/Jodit.ts (1232,28): Property 'defaultMode' does not exist on type 'Config'.
/var/www/html/git/inteleagent/node_modules/jodit/src/Jodit.ts (1234,21): Property 'saveModeInStorage' does not exist on type 'Config'.
/var/www/html/git/inteleagent/node_modules/jodit/src/Jodit.ts (1244,21): Property 'readonly' does not exist on type 'Config'.
/var/www/html/git/inteleagent/node_modules/jodit/src/Jodit.ts (1249,21): Property 'disabled' does not exist on type 'Config'.

I'm working with Angular 4 , please help me in resolving this issue.

**Comment by MrElectroNick** [comment]
Angular v4 is no longer supported. Supported versions are from V8 and up
