### ISSUE TITLE
set up responsive images

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#55]
Hello,

Is there an option to get the images to adjust with the relevant proportion (width x height) across multiple screens? In the same way the text adjusts itself and its fully responsive, I'd like the images to do so in order to get the articles well formed.

I'm not sure if there is a setting somewhere for this or do I have to do it myself? I have tried through the styles of the images themselves but that does not work.

My setup in Angular 9:
```
"jodit": "3.3.22",
"jodit-angular": "1.0.99",
```

Many thanks!

**Comment by MrElectroNick** [comment]
Hi @CarlosTorrecillas please report this issue to [Jodit main repository](https://github.com/xdan/jodit/issues)
