### ISSUE TITLE
CSS not being saved

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#56]
When you edit image styles and try to apply certain CSS directly in the input, the styles are not saved. Note that I'm trying to go from certain width and height to width 100% and height auto. Not sure if that something could prevent the CSS from being saved.

My setup:
```
"angular": "9.1.1"
"jodit": "3.3.22",
"jodit-angular": "1.0.99"
```

**Comment by MrElectroNick** [comment]
@CarlosTorrecillas please update jodit-angular to latest version and if this doesn't fix your issue - please report it to an [editor repository](https://github.com/xdan/jodit)
