### ISSUE TITLE
Tab-focus from input to editor

### ISSUE THREAD

**Issue by jebkor** [jodit/jodit-angular#72]
When I try to tab from a regular input to the Jodit Editor, it skips past the editor to the next interactable element instead.

### Steps to reproduce the issue
1.  Install "Jodit" and "Jodit Angular" dependencies according to the installation guide (see versions used at the bottom)
2. Create a regular input element before a jodit element and then another regular input element after the jodit one. Doesn't have to be a form
3. Try and tab from the regular input element to the jodit element. You should see that the tab selection skips over the jodit editor, only to focus the other regular input element

#### What's the expected result?
The expection was that the editor would become focused when tabbing into it.

#### What's the actual result?
Tabbing into the editor ignores the editor and tabs past it, to focus other interactable elements after it.

#### Versions
- Angular 8.2.14
- Jodit 3.6.2
- Jodit Angular 1.0.122

**Comment by MrElectroNick** [comment]
Hi @B1nary1nput this issue is not related to angular wrapper. Please report this issue to main [Jodit repository](https://github.com/xdan/jodit/issues)
