### ISSUE TITLE
OnBlur

### ISSUE THREAD

**Issue by stockmind** [jodit/jodit-angular#8]
I've seen your latest commits about eventHandling, i'm looking to use (blur) to hide the editor but can't trigger it. I see the OnFocus event on your code but not the OnBlur. Is it possible to add it? Will it work just adding it?

I can make a pull request if required

**Comment by pwiegers** [comment]
Hi,
sorry to bother you, but I cannot get any blur event to fire:
`                    <JoditEditor
                        editorRef={this.setRef2}
                        value={this.state.aantekeningen}
                        config={this.configSmall}
                        onChange={this.handleChange}
                        onBlur={this.handleBlur}
                    />
`
handleChange fires, but handleBlur does not. Am I doing something wrong?
regards,

Paul

**Comment by pwiegers** [comment]
Ah, I found out how to do this:
`    config = {
        events: {
            blur: () => {
                this.handleBlur()    
            }
        }
    }  
`
And then add the config to the editor...
