### ISSUE TITLE
I got an error 'has no selector, please add it!' when run 'ng build --prod'

### ISSUE THREAD

**Issue by klower** [jodit/jodit-angular#87]
Angular7:

ERROR in : Directive ɵa in node_modules/jodit-angular/jodit-angular.d.ts has no selector, please add it!

**Comment by klower** [comment]
anyone can help?

**Comment by MrElectroNick** [comment]
Angular 7 is no longer supported not by angular developers nor this package. Please try to upgrade to at least Angular V8 and check an issue is resolved
