### ISSUE TITLE
Insert image from computer

### ISSUE THREAD

**Issue by CarlosTorrecillas** [jodit/jodit-angular#9]
Is it possible to add an image from the local computer as opposed to setting the URL of it? I couldn't find that option in the playground.

Thanks!

**Comment by xdan** [comment]
Do you want insert as base64 image ?

**Comment by CarlosTorrecillas** [comment]
Yes, I’d like to add an image from the the computer. I guess if there is an event I could hook into then I could try to set a chosen base64 image. Is there any option to enable an extra button so that I can get that functionality in?

**Comment by jodit** [comment]
Hi, added https://xdsoft.net/jodit/play.html?uploader%5BinsertImageAsBase64URI%5D=true option

**Comment by CarlosTorrecillas** [comment]
Many thanks for that.  updated to v1.0.47 and I can see now the option available which works perfectly fine when to drag an image however the "click" option doesn't always work. You have to click multiple times to get the explorer (file selector) up. I'm using angular 5.2.9 but I don't think that makes any difference. is that something you could quickly check? The playground though works like a charm.

Thanks!
