### ISSUE TITLE
Module not found: Error: Can't resolve 'jodit'

### ISSUE THREAD

**Issue by dvdnhm** [jodit/jodit-angular#93]
I just created a new project with Angular 12.2.0 and followed the instructions.

I am getting error below:
./node_modules/jodit-angular/__ivy_ngcc__/fesm2015/jodit-angular.js:94:21-37 - 
Error: Module not found: Error: Can't resolve 'jodit' in 'xxxxxx\jodit-demo\node_modules\jodit-angular\__ivy_ngcc__\fesm2015'

any suggestions?

**Comment by MrElectroNick** [comment]
Hi @dvdnhm you need to include jodit itself along with jodit-angular within your package json so install it also

**Comment by dvdnhm** [comment]
it should not be relevant but somehow it is... if anyone gets the same problem, install Jodit before Jodit-Angular
